---
gapper-server-agent-db:
  dsn: mysql:dbname=${GAPPER_SERVER_AGENT_DB_NAME};host=${GAPPER_SERVER_AGENT_DB_HOST};port=${GAPPER_SERVER_AGENT_DB_PORT}
  username: ${GAPPER_SERVER_AGENT_DB_USER}
  password: ${GAPPER_SERVER_AGENT_DB_PASSWORD}
...
