---
#auth-default-login: AUTH TYPE
#auth-default-group: AUTH TYPE
#auth-default-group-401: AUTH TYPE
#auth-default-user-401: AUTH TYPE
#auth-default-done: AUTH TYPE
auth:
  gapper:
    icon: assets/img/gapper-auth-gapper/logo.png
    name: Gapper
    show: ${SHOW_LOGIN_TYPE_GAPPER}
server_home: ${GAPPER_URL:='http://gapper.in/'}
# proxy:
#   - url: http://url
#     proxy: http://proxy.url
# 3rd:
#   sso:
#     condition: sso
#     class: \Gini\Gapper\SSO
#     params:
#       url: SSO-URL
#       type: cookie
#       cookie: 
#         key: COOKIE-KEY
#         method: METHOD
#         result: RESULT-KEY
#         gapper-source: GAPPER-SOURCE 
gapper-client-use-agent-data: ${GAPPER_CLIENT_USE_AGENT_DATA:='false'}
...
